### ISSUE TITLE
Make the plugin work with snapshot versions

### ISSUE THREAD

**Issue by andye2004** [AxonFramework/IdeaPlugin#107]
In `ProjectUtils.kt` file the following regex:-

```kotlin
val versionRegex = Regex("^4\\.\\d+\\.\\d+$")
```

prevents the plugin from working with snapshot versions, I'm unclear as to why you would want to restrict the plugin from working with snapshot versions, if there isn't a good reason for this can the regex be updated to make it compatible?

EDIT: On further investigation it's the processing to extract the version number for comparison with the above noted regex that is the source of the trouble.

**Comment by Morlack** [comment]
This has been implemented through PR #108
