### ISSUE TITLE
Axon version detection did not work properly in v0.7.2

### ISSUE THREAD

**Issue by camyhsu** [AxonFramework/IdeaPlugin#119]
### Basic information

* JDK version:
```
java version "11.0.15" 2022-04-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.15+8-LTS-149, mixed mode)
```
* Complete executable reproducer if available (e.g. GitHub Repo):
Not available - the context is in a proprietary commercial development that I am not allowed to disclose the Intellectual Property.

### Steps to reproduce

1. Create a custom library code with the word axon in the package name somewhere, for example, com.abc.myutil.axoninfrastructure.SampleExtension.java -- the content of the sample code does not matter as far as I can tell.
2. Package the library code into a jar, with the artifact name (that is, the jar name) containing the word axon.  This can be done locally as a snapshot version.  For example, the above library code can be packaged by Maven or Gradle into the local `~/.m2/repository/com/abc/myutil/axon-infrastructure/0.0.0-SNAPSHOT/axon-infrastructure-0.0.0-SNAPSHOT.jar`
3. Create another application code in a different project and make it depends on the Axon framework and the above custom library code.
4. Install Axon Framework plug-in v0.7.2 and restart IntelliJ.

### Expected behaviour

The Axon Framework plug-in should be enabled and working without problem.

### Actual behaviour

The Axon Framework plug-in v0.7.2 disabled itself with an error notification.  See the attached screenshot.
The plug-in versions before v0.7.2 worked without problem for the same code / context.

<img width="374" alt="Plug-inDisabledNotification" src="https://user-images.githubusercontent.com/130092/179415640-74044a43-baa5-474e-a034-1a68243f3898.png">

**Comment by ianthetechie** [comment]
I'm getting a similar error complaining about the axon-kotlin dependency as well.

![image](https://user-images.githubusercontent.com/2140440/179452556-7ffa461d-80f6-4347-9664-d08703836205.png)

**Comment by Morlack** [comment]
Hello @ianthetechie and @camyhsu, thanks for reporting the issue! I will fix it immediately today, my apologies for the introduced bug

**Comment by Morlack** [comment]
I have created a fix and submitted it to Jetbrains (version `0.7.3`). Its currently waiting approval.

https://github.com/AxonFramework/IdeaPlugin/releases/tag/v0.7.3

**Comment by Morlack** [comment]
It took Jetbrains some time, but the update was approved a few hours ago:

> Version 0.7.3 of the Axon Framework plugin has been approved by JetBrains and is now publicly available at the following link: https://plugins.jetbrains.com/plugin/18628-axon-framework/versions/stable/196471.
