### ISSUE TITLE
IntelliJ Idea 2022.3 support

### ISSUE THREAD

**Issue by dcebotarenco** [AxonFramework/IdeaPlugin#159]
### Enhancement Description

Axon plugin 0.7.3 is not supported by 2022.3 after upgrading the IntelliJ Idea 

Running: 
_IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-223.7571.182, built on November 29, 2022_

### Current Behaviour

The error **"Incompatible: requires IDE build 222.* or earlier"** is displayed in the **Plugins** settings

### Wanted Behaviour

Would be nice to have the plugin supported by IntelliJ IDEA 2022.3

### Possible Workarounds

Rollback to the earlier IntelliJ Idea version or Disable the plugin temporarily

**Comment by Morlack** [comment]
Hello @dcebotarenco , thanks for reporting! I am currently working on a release, it should be out today. I'll give you a heads up when it's available here.

**Comment by dcebotarenco** [comment]
Hey, @Morlack I see you've released the new plugin version. Thank you.
I guess we can close this.

**Comment by Morlack** [comment]
You are right, @dcebotarenco! I had to wait for approval, but it's out now. Enjoy, and leave any feedback or additions you would like to see!
