### ISSUE TITLE
Axon plugin 0.8.1 is not supported by IDEA 2023.2

### ISSUE THREAD

**Issue by bradskuse** [AxonFramework/IdeaPlugin#234]
### Basic information

* JDK version: 17.0.7+7-b1000.6 aarch64

<img width="327" alt="Screenshot 2023-07-27 at 1 55 05 pm" src="https://github.com/AxonFramework/IdeaPlugin/assets/998188/e2aed90e-c9a6-4920-a064-2af2b90d7549">

<img width="459" alt="Screenshot 2023-07-27 at 1 55 30 pm" src="https://github.com/AxonFramework/IdeaPlugin/assets/998188/62bb98c5-f0a8-4122-b819-b5b0abee4574">

### Steps to reproduce

Open IntelliJ IDEA 2023.2 (Ultimate Edition)
Axon Plugin 0.8.1 installed

### Expected behaviour

Plugin works

### Actual behaviour

Error:

Plugin 'Axon Framework' (version '0.8.1') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IU-232.8660.18

**Comment by meierw** [comment]
Just chiming in that I'd also like this to be fixed. The plugin not working on the newer IntelliJ version is a bit of a bummer. :bow:

**Comment by smcvb** [comment]
We released 0.8.2 of the IntelliJ Plugin yesterday, as you can see [here](https://github.com/AxonFramework/IdeaPlugin/releases/tag/v0.8.2).
It may take some time before it's up on the marketplace, though; that's sadly enough, not something we can control.

Be sure to notify us once you have the plugin in place.
Then we can close this issue accordingly.

**Comment by smcvb** [comment]
Just updated my IntelliJ to 2023.2, as well as the Axon plugin. 
All seems to work on my end.
Nonetheless, be sure to update once it works for either of you, @bradskuse and @meierw!

**Comment by bradskuse** [comment]
Confirming I've updated and it works.

Thank you!

**Comment by smcvb** [comment]
Awesome, happy to hear that, @bradskuse! I close this issue as resolved.
