### ISSUE TITLE
No Creator Found: with kotlin/gradle + java/maven multi-module project

### ISSUE THREAD

**Issue by KahigaKiguru** [AxonFramework/IdeaPlugin#256]
### Basic information

* JDK version: 20
* Complete executable reproducer if available (e.g. GitHub Repo):

### Steps to reproduce
I run IntelliJ IDEA 2023.2.4 (Ultimate Edition) and Axon Framework Plugin v0.8.3

I have a global message library that contains all our commands, events, queries and projections, previously written in Java as 
Java Records then rewritten as Kotlin data classes.

This library is consumed by spring microservices that run with java 20, axon-starter 4.9.0 and spring-boot 3.1.5

When the Library was written in Java, the plugin could easily Identify and route all message types within the multimodule project. However, with kotlin nested data classes, the plugin errs with the message 'No creators of this Message Payload were found'

This happens with events, queries and commands.

I'm not entirely sure if it's the IDE since I'm running the latest version at the time of writing. 

Writing large code-bases with the axon plugin malfunctioning is very difficult.

Thanks!

### Expected behaviour

The plugin should route all message types and their handlers regardless of the implementation language so long as it is supported

### Actual behaviour

The plugin errs with message :: ```No creators of this Message Payload were found``` for commands, events and queries with DTOs implemented as nested Kotlin Data Classes.    Please describe the actual behaviour as discovered.

**Comment by KahigaKiguru** [comment]
Update, Turns out I need to use wildcard imports for nested data classes so that the plugin recognizes them as valid messages.

**Comment by KahigaKiguru** [comment]
I'll go ahead and close the issue - solved.

**Comment by smcvb** [comment]
Happy to hear you've found a solution to your predicament yourself, @KahigaKiguru! This info should proof useful for others facing the same situation.
