### ISSUE TITLE
Update to IntellIJ 2023.3

### ISSUE THREAD

**Issue by wolfomat** [AxonFramework/IdeaPlugin#268]
I am pretty happy with this plugin, but now it does not work, after i've update to the latest intelliJ 2023.3

Could you update the plugin, please?

thanks

**Comment by smcvb** [comment]
Thanks for the interest, @wolfomat. We'll try to release a new version of the plugin ASAP.
We'll close this issue once the release is successful. So, stay tuned :-)

**Comment by CodeDrivenMitch** [comment]
Jetbrains notified that the new version is approved. Please update the plugin and it should work with the new InteliJ.

Version 0.8.4 of the Axon Framework plugin has been approved by JetBrains and is now publicly available at the following link: https://plugins.jetbrains.com/plugin/18628-axon-framework/versions/stable/452071.

**Comment by wolfomat** [comment]
confirm working. thanks
