### ISSUE TITLE
Navigation between message, producer and consumers should include handler listening to interface or superclasses

### ISSUE THREAD

**Issue by coulas** [AxonFramework/IdeaPlugin#285]
### Enhancement Description

When I click on Axon navigation icon close to a message instantiation or definition or handling,
A popup shows me the list of other interactions with this exact type and its type hierarchy and interfaces.

### Current Behaviour

The popup lists only concrete-type usage.
EventHandler listening to an interface receives all implementations of this interface at runtime, but Axon plugin's navigation does not show them.

### Wanted Behaviour

Being able to see all usage of a message in axon's navigation, including usage per supertypes and interfaces and maybe separated from concrete usage by a line as collective usages are not the same kind of usage than per concrete name.

### Possible Workarounds

IntelliJ indirect navigation.

**Comment by smcvb** [comment]
Hi @coulas! 

Mainly letting you know we've spotted your issue and will take a look at it relatively soon.
There are some other tasks the team needs to take care of first.
But the plugin will receive some love in the foreseeable future.

So, stay tuned!

**Comment by coulas** [comment]
Thank you !
