### ISSUE TITLE
Support for intellij 2024.2

### ISSUE THREAD

**Issue by mjeffrey** [AxonFramework/IdeaPlugin#286]
### Enhancement Description
Please support the latest release of intellij 2024.2.
I see there is a release for 0.8.7 but it is not yet available in the intellij.

### Current Behaviour
With the latest release of Intellij the plugin 0.8.6 no longer works. 

![image](https://github.com/user-attachments/assets/9e06a98f-0865-4b2f-ae13-0ab2cc3f0fd2)

**Comment by CodeDrivenMitch** [comment]
Hi @mjeffrey, thanks for reporting this! I saw something went wrong with the release I intended and have corrected this issue. Version 0.8.7 is now approved by Jetbrains and available!
