### ISSUE TITLE
Axon plugin gives false highlights about non existing properties when they are defined in a superclass

### ISSUE THREAD

**Issue by guymahieu** [AxonFramework/IdeaPlugin#307]
In our project we get warnings on SagaEventHandlers that rely on an associationProperty from a superclass of the messsage. This works in Axon but is indicated as a problem by the plugin.

I have created a PR (https://github.com/AxonFramework/IdeaPlugin/pull/306) which fixes that for the SagaEventHandlers, but there are probably other cases where this applies (routingKeys?). We do not have this case in our project at the moment, so I did not change that.

**Comment by smcvb** [comment]
Thanks for filing this concern with us, @guymahieu, and for providing a pull request, too! We'll take a look at this ASAP.
