### ISSUE TITLE
Plugin is incompatible with K2 Mode

### ISSUE THREAD

**Issue by jacoadriaansen** [AxonFramework/IdeaPlugin#315]
### Enhancement Description
IntelliJ recently shipped a stable version of [k2 mode](https://blog.jetbrains.com/idea/2024/11/k2-mode-becomes-stable/). The Axon Framework plugin isn't compatible with the kotlin plugin when IntelliJ has k2 mode enabled.

### Current Behaviour
Currently you can either use k2 mode or the Axon Framework plugin
![image](https://github.com/user-attachments/assets/fb22bb89-38c0-4e70-bede-127767ae9693)

### Wanted Behaviour
Please make the plugin compatible with the kotlin-plugin and k2 mode.

### Possible Workarounds
To use the axon framework plugin disable k2 mode in IntelliJ.

**Comment by smcvb** [comment]
Thanks for filing this issue with us, @jacoadriaansen! 
We are aware the plugin isn't compatible with K2 mode.
Sadly, we are pretty sure the effort is going to be rather extensive to make it work for K2 mode.
As such, I am hardpressed to provide you a date when this will be resolved.

If anything, we'll be sure to update this issue accordingly for it's progress.

**Comment by CodeDrivenMitch** [comment]
Hello @jacoadriaansen! I have made the IDEA plugin K2-mode compliant with the 0.9.0 release. As such, I will resolve the issue. Let me know if you run into any issues.
