### ISSUE TITLE
Plugin not working with Axon 4

### ISSUE THREAD

**Issue by alionx** [AxonFramework/IdeaPlugin#8]
I have installed the plugin to work with Intelij IDEA 2019.1.2. I can't see if it is working because the icons on the left (called gutter icons) do not appear.

**Comment by smcvb** [comment]
What version of Axon Framework are you using @alionx?

**Comment by alionx** [comment]
Axon Server 4.1 and framework 4.1.1

**Comment by alionx** [comment]
@smcvb any update on if/when it will be supported?

**Comment by smcvb** [comment]
Glad to hear your interest in the plugin @alionx.
At the moment, we are quite hard at work at AxonIQ to provide features for Axon Server and Axon Framework. 
Sadly, to an extent, that the overall priority of the plugin compared to server and framework is quite low.

As such, I'd be hard pressed at the moment to provide you a date when it will be supported.
This is however from our time management perspective. The plugin _is_ open source, just like the framework. Thus any help in this area is, as always, highly appreciated.

**Comment by spanierm** [comment]
Oh, that is really unfortunate, @smcvb. I would love to use the plugin with Axon 4 as well. Fingers crossed that you find some time for it.

**Comment by Morlack** [comment]
Hello @mod-enter and @alionx , the plugin has been updated to support Axon Framework 4.x, as well as Kotlin source code. You can download it from the Jetbrains marketplace. We would love to receive any feedback you have, as well as suggestions for additions to the plugin. Please raise an issue if you experience or think of anything. 
Thanks for your patience!
